In [2]:
import pandas as pd
dataset = pd.read_csv("/content/ObesityDataSet_raw_and_data_sinthetic.csv", on_bad_lines='skip')

FileNotFoundError: ignored

In [ ]:
dataset.head(5)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [ ]:
dataset.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [3]:
dataset.isnull().sum()

NameError: ignored

In [ ]:
dataset['Gender'].replace('Female',0, inplace=True)
dataset['Gender'].replace('Male',1, inplace=True)

In [ ]:
dataset['family_history_with_overweight'].replace('no',0, inplace=True)
dataset['family_history_with_overweight'].replace('yes',1, inplace=True)

In [ ]:
dataset['SMOKE'].replace('no',0, inplace=True)
dataset['SMOKE'].replace('yes',1, inplace=True)

In [ ]:
dataset['NObeyesdad'].replace('Insufficient_Weight',0, inplace=True)
dataset['NObeyesdad'].replace('Normal_Weight',1, inplace=True)
dataset['NObeyesdad'].replace('Overweight_Level_I',2, inplace=True)
dataset['NObeyesdad'].replace('Overweight_Level_II',2, inplace=True)
dataset['NObeyesdad'].replace('Obesity_Type_I',3, inplace=True)
dataset['NObeyesdad'].replace('Obesity_Type_II',3, inplace=True)
dataset['NObeyesdad'].replace('Obesity_Type_III',3, inplace=True)

In [ ]:
dataset = dataset.drop(["MTRANS","FAVC","FCVC","NCP","CAEC","CH2O","SCC","FAF","TUE","CALC"], axis=1)
dataset

,Gender,Age,Height,Weight,family_history_with_overweight,SMOKE,NObeyesdad
0,0,21.000000,1.620000,64.000000,1,0,1
1,0,21.000000,1.520000,56.000000,1,1,1
2,1,23.000000,1.800000,77.000000,1,0,1
3,1,27.000000,1.800000,87.000000,0,0,2
4,1,22.000000,1.780000,89.800000,0,0,2
...,...,...,...,...,...,...,...
2106,0,20.976842,1.710730,131.408528,1,0,3
2107,0,21.982942,1.748584,133.742943,1,0,3
2108,0,22.524036,1.752206,133.689352,1,0,3
2109,0,24.361936,1.739450,133.346641,1,0,3
2110,0,23.664709,1.738836,133.472641,1,0,3

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 6].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=40)
xtrain.shape, xtest.shape

((1688, 6), (423, 6))

In [ ]:
norm = StandardScaler()
xtrain = norm.fit_transform(xtrain)
xtest = norm.transform(xtest)

In [ ]:
from sklearn.svm import SVC
from sklearn import metrics

svc=SVC()
svc.fit(xtrain,ytrain)
y_pred=svc.predict(xtest)

print('Accuracy Score:')
print(metrics.accuracy_score(ytest,y_pred))

Accuracy Score:
0.9314420803782506

In [ ]:
my_pred = svc.predict([[0,22,1.54,89,0,1]]) #Gender(0-M,1-F),age,height,weight,family history(),smoking habit
if my_pred==1:
  print("You are Normal Weight")
elif my_pred==0:
  print("You are Insufficient in Weight")
elif my_pred==2:
  print("You are Over Weight")
else:
  print("You have Obesity")

You are Over Weight